#!/usr/bin/env bash
# Compiles Support/AppIcon.icon into Support/Assets.car.
#
# macOS 26 themes the app icon in the Finder, Launchpad and the Dock (while the
# app is not running) from an `Assets.car` carrying an Icon Composer icon stack
# with one rendition per appearance. A legacy `.icns` cannot express that: it is
# a single image, so those surfaces stayed on the dark tile no matter what the
# system's icon style was. `scripts/build-app.sh` still ships the `.icns` for
# macOS 15 and for the DMG volume icon.
#
# Usage: build-app-icon.sh [--check]
#   (no flag)  regenerate Support/Assets.car
#   --check    verify the committed Support/Assets.car is present and themed,
#              without invoking actool
#
# The result is committed rather than rebuilt on every app build: actool has had
# `.icon` regressions across Xcode releases, and compiling here would tie the
# release workflow to one toolchain. Re-run this script whenever the artwork or
# `icon.json` changes.
#
# Exit codes: 0 = the catalog is present and carries both appearances,
#             1 = the catalog is missing or is not themed,
#             2 = the arguments or the toolchain are unusable.

set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
MODE="${1:-build}"

ICON_SOURCE="$ROOT/Support/AppIcon.icon"
ICON_JSON="$ICON_SOURCE/icon.json"
ICON_ASSETS="$ICON_SOURCE/Assets"
CATALOG="$ROOT/Support/Assets.car"

case "$MODE" in
    build|--check) ;;
    *)
        echo "Usage: $0 [--check]" >&2
        exit 2
        ;;
esac

# Every appearance the system can ask an app icon for. A catalog that is missing
# one of these silently falls back to the flat `.icns` for that style.
REQUIRED_APPEARANCES=(
    NSAppearanceNameAqua
    NSAppearanceNameDarkAqua
)

verify_catalog() {
    local catalog="$1"
    if [[ ! -f "$catalog" ]]; then
        echo "Error: $catalog does not exist. Run scripts/build-app-icon.sh." >&2
        return 1
    fi

    local listing
    listing="$(assetutil --info "$catalog" 2>/dev/null || true)"
    if [[ -z "$listing" ]]; then
        echo "Error: assetutil could not read $catalog." >&2
        return 1
    fi

    # `IconImageStack` is what the system themes; a plain `Icon Image` would mean
    # this compiled as a legacy icon and the appearance variants were dropped.
    if ! grep -q 'IconImageStack' <<<"$listing"; then
        echo "Error: $catalog has no IconImageStack; the icon is not themed." >&2
        return 1
    fi

    local appearance
    for appearance in "${REQUIRED_APPEARANCES[@]}"; do
        if ! grep -q "$appearance" <<<"$listing"; then
            echo "Error: $catalog has no $appearance rendition." >&2
            return 1
        fi
    done

    return 0
}

if [[ "$MODE" == "--check" ]]; then
    if verify_catalog "$CATALOG"; then
        echo "Assets.car check passed (IconImageStack with light and dark renditions)."
    else
        exit 1
    fi
    exit 0
fi

if [[ ! -f "$ICON_JSON" ]]; then
    echo "Error: missing $ICON_JSON." >&2
    exit 1
fi

if ! command -v xcrun >/dev/null 2>&1; then
    echo "Error: xcrun is required; install Xcode." >&2
    exit 2
fi

if ! xcrun --sdk macosx --find actool >/dev/null 2>&1; then
    echo "Error: actool is required; it ships with Xcode 26 or later." >&2
    exit 2
fi

# The icon document is self-contained, so its layers are the same two tiles the
# bundle already ships. Copy them in rather than tracking a third pair.
for variant in AppIcon-Light.png AppIcon.png; do
    if [[ ! -f "$ROOT/Support/$variant" ]]; then
        echo "Error: missing Support/$variant." >&2
        exit 1
    fi
done
mkdir -p "$ICON_ASSETS"
cp "$ROOT/Support/AppIcon-Light.png" "$ICON_ASSETS/AppIcon-Light.png"
cp "$ROOT/Support/AppIcon.png" "$ICON_ASSETS/AppIcon-Dark.png"

# actool does not create its output directory.
OUTPUT_DIR="$(mktemp -d "${TMPDIR:-/tmp}/StatusTrioIcon.XXXXXX")"
trap 'rm -rf "$OUTPUT_DIR"' EXIT

xcrun --sdk macosx actool "$ICON_SOURCE" \
    --compile "$OUTPUT_DIR" \
    --output-format human-readable-text \
    --notices --warnings --errors \
    --output-partial-info-plist "$OUTPUT_DIR/partial.plist" \
    --app-icon AppIcon \
    --include-all-app-icons \
    --enable-on-demand-resources NO \
    --development-region en \
    --target-device mac \
    --minimum-deployment-target 26.0 \
    --platform macosx

if [[ ! -f "$OUTPUT_DIR/Assets.car" ]]; then
    echo "Error: actool did not produce Assets.car." >&2
    exit 1
fi

cp "$OUTPUT_DIR/Assets.car" "$CATALOG"

# Fail loudly here instead of shipping an unthemed icon that only shows up as
# "the icon never changes with the system".
if ! verify_catalog "$CATALOG"; then
    exit 1
fi

# actool also emits an AppIcon.icns from the icon document. It is deliberately
# not used: the bundle's .icns is generated by build-app.sh from the approved
# 1024px tile, which is what macOS 15 and the DMG volume show.
echo "Wrote $CATALOG"
